import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { read, root, fontGlyphs, resolvedGlyphs, validateCatalog, legacySources } from './manifest.mjs';

export const glyphVariable = (code, role) => `@ss-glyph-${code}-${role}`;
const comment = value => value.replace(/[\r\n]+/g, ' ');

export function renderLess(catalog) {
    const header = '// Generated by scripts/generate-less.mjs. Edit data/sets.json instead.\n';
    const variables = [header];
    const mappings = [header];
    const names = new Set();
    for (const group of catalog.groups) {
        variables.push(`// ${comment(group.name)}`);
        mappings.push(`// ${comment(group.name)}`);
        for (const set of catalog.sets.filter(set => set.group === group.id)) {
            const glyphs = resolvedGlyphs(set, catalog.sets);
            variables.push(`// ${comment(set.name)}`);
            for (const [role, glyph] of Object.entries(glyphs)) {
                const name = glyphVariable(set.code, role);
                if (names.has(name)) throw new Error(`Duplicate glyph variable: ${name}`);
                names.add(name);
                variables.push(`${name}: "\\${glyph}";`);
            }
            const selectors = [set.code, ...(set.aliases ?? [])].map(code => `.@{ss-prefix}-${code}:before`).join(',\n');
            mappings.push(`${selectors} { content: ${glyphVariable(set.code, 'default')}; } // ${comment(set.name)}`);
        }
        variables.push('');
        mappings.push('');
    }
    return { 'less/glyphs.less': variables.join('\n'), 'less/icons.less': mappings.join('\n') };
}

export async function prepareLess() {
    const catalog = JSON.parse(await read('data/sets.json'));
    const schema = JSON.parse(await read('data/sets.schema.json'));
    const errors = validateCatalog(catalog, schema, { font: await fontGlyphs() });
    if (errors.length) throw new Error(errors.join('\n'));
    const files = renderLess(catalog);
    // Compile with fresh variables in memory, so stale/missing generated files
    // cannot block a valid manifest change or a clean regeneration.
    const sources = await legacySources({ includeDocs: false, generatedFiles: files });
    const layerErrors = validateCatalog(catalog, schema, sources);
    for (const file of ['duo', 'border']) {
        if (/content:\s*["']\\[\da-f]+/i.test(sources[file].source)) {
            layerErrors.push(`less/${file}.less: use named glyph variables instead of literal codepoints.`);
        }
    }
    if (layerErrors.length) throw new Error(layerErrors.join('\n'));
    return { catalog, files };
}

export async function generateLess() {
    const { files } = await prepareLess();
    for (const [path, source] of Object.entries(files)) {
        const current = await read(path).catch(error => { if (error.code !== 'ENOENT') throw error; return null; });
        if (current !== source) await writeFile(`${root}${path}`, source);
    }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    try {
        if (process.argv.length === 3 && process.argv[2] === '--check') {
            const { catalog } = await prepareLess();
            console.log(`Manifest valid: ${catalog.sets.length} entries; glyphs and handwritten layer rules validated.`);
        } else if (process.argv.length === 2) {
            await generateLess();
            console.log('Generated LESS glyph variables and default mappings.');
        } else {
            throw new Error('Usage: node scripts/generate-less.mjs [--check]');
        }
    } catch (error) {
        console.error(error.message);
        process.exitCode = 1;
    }
}
