sets = {
  "Core": {
    "lea": "Alpha",
    "leb": "Beta",
    "2ed": "Unlimited",
    "3ed": "Revised",
    "4ed": "Fourth Edition",
    "5ed": "Fifth Edition",
    "6ed": "Sixth Edition",
    "7ed": "Seventh Edition",
  },
  "Expansion": {
    "arn": "Arabian Nights",
    "atq": "Antiquities",
    "leg": "Legends",
    "drk": "The Dark",
    "fem": "Fallen Empires",
    "ice": "Ice Age",
    "hml": "Homelands",
    "all": "Alliances",
    "mir": "Mirage",
    "vis": "Visions",
    "wth": "Weatherlight",
    "tmp": "Tempest",
    "sth": "Stronghold",
    "exo": "Exodus",
    "usg": "Urza's Saga",
    "ulg": "Urza's Legacy",
    "uds": "Urza's Destiny",
    "mmq": "Mercadian Masques",
    "mmq": "Mercadian Masques",
    "nem": "Nemesis",
    "pcy": "Prophecy",
    "inv": "Invasion",
    "pls": "Planeshift",
    "apc": "Apocalypse",
    "ody": "Odyssey",
    "tor": "Torment",
    "jud": "Judgment",
    "ons": "Onslaught",
    "lgn": "Legions",
    "scg": "Scourge",
  },
  "Command": {
    "pvan": "Vanguard",
  },
  "Reprint": {
    "sum": "Summer Magic",
    "fbb": "Foreign Black Border",
    "4bb": "4th Edition Black Border",
    "chr": "Chronicles",
    "ren": "Renaissance",
    "rin": "Rinascimento",
    "ath": "Anthologies",
    "brb": "Battle Royale Box Set",
    "btd": "Beatdown Box Set",
    "dkm": "Deckmasters",
  },
  "Supplemental": {},
  "Digital": {
    "past": "Astral Cards",
    "prm": "Magic Online Promos",
  },
  "Beginner": {
    "itp": "Introductory 2-Player Set",
    "por": "Portal",
    "p02": "Portal Second Age",
    "s99": "Starter 1999",
    "ptk": "Portal Three Kingdoms",
    "s00": "Starter 2000",
  },
  "Premium": {
    "ced": "Collectors' Edition",
    "cei": "Intl. Collectors' Edition",
  },
  "Promo": {
    "pdrc": "Dragon Con",
    "phpr": "HarperPrism Book Promos",
    "pmei": "Media Inserts",
    "pmtg": "MTG Logo Promos",
    "pgc98": "Gen Con 1998 Oversized Promo",
    "palp": "APAC Lands",
    "pgru": "Guru",
    "fnm": "Friday Night Magic",
    "pal00": "Arena League",
    "pelp": "Euro Lands",
    "mpr": "Magic Player Rewards",
    "psdg": "Sega Dreamcast Promos",
  },
  "Standalone": {
    "ugl": "Unglued",
  },
  "Alternative": {
    "legchr": "Legends (Chronicles)",
    "po": "Portal (Gatherer)",
    "wl": "Weatherlight (Gatherer)",
    "brbalt": "Battle Royale (Alternate)",
  }
}
